"""Version-aware journal reading (docs/SCHEMA.md reader rules).

Covers: header hard-requirement, explicit legacy mode with contamination
checks, mid-stream shard-boundary headers, exact non-finite sentinels with
alarm-direction semantics (the schema review's verdict-inversion finding),
and the committed v1 fixture generated by the post-break library.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tracked_tools.reduce import ReducerConfig, core

REPO = Path(__file__).resolve().parents[2]
V1_FIXTURE = REPO / "tests" / "parity" / "fixtures" / "v1_small.jsonl"

HEADER = {"schema": 1, "library_version": "1.0.0",
          "keys": ["op", "at", "id", "in", "val", "cond", "rel_err",
                   "prov_vars", "prov_consts"]}


def rec(op="mul", ident="m#1@integral=k/sample=0", val=1.0, cond=1.0,
        rel_err=1e-16, **extra):
    r = {"op": op, "at": "f.h:fn:3", "id": ident, "in": ["a", "b"], "val": val,
         "cond": cond, "rel_err": rel_err, "prov_vars": ["a"], "prov_consts": []}
    r.update(extra)
    return r


def write(tmp_path, lines, name="j.jsonl"):
    p = tmp_path / name
    p.write_text("".join(json.dumps(l) + "\n" for l in lines), encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# mode selection and contamination checks
# ---------------------------------------------------------------------------

def test_headerless_hard_fails_in_v1_mode(tmp_path):
    j = write(tmp_path, [rec()])
    with pytest.raises(ValueError, match="legacy"):
        core.reduce_journal(j)


def test_legacy_mode_hard_fails_on_v1_header(tmp_path):
    j = write(tmp_path, [HEADER, rec()])
    with pytest.raises(ValueError, match="not pre-v1"):
        core.reduce_journal(j, legacy=True)


def test_unknown_schema_hard_fails(tmp_path):
    j = write(tmp_path, [{"schema": 99}, rec()])
    with pytest.raises(ValueError, match="unsupported journal schema"):
        core.reduce_journal(j)


def test_null_in_v1_hard_fails(tmp_path):
    j = write(tmp_path, [HEADER, rec(val=None)])
    with pytest.raises(ValueError, match="legacy contamination"):
        core.reduce_journal(j)


@pytest.mark.parametrize("bad", ["NaN", "Infinity", "+inf", "1.5", " inf"])
def test_non_sentinel_strings_hard_fail(tmp_path, bad):
    j = write(tmp_path, [HEADER, rec(cond=bad)])
    with pytest.raises(ValueError, match="sentinel"):
        core.reduce_journal(j)


def test_empty_file_is_empty_journal(tmp_path):
    p = tmp_path / "empty.jsonl"
    p.write_text("", encoding="utf-8")
    rep = core.reduce_journal(p)
    assert rep["integrals"] == {} and rep["nonfinite_records"] == 0


def test_header_only_journal_is_empty(tmp_path):
    j = write(tmp_path, [HEADER])
    rep = core.reduce_journal(j)
    assert rep["integrals"] == {} and rep["no_id_records"] == 0


# ---------------------------------------------------------------------------
# concatenation: mid-stream headers are shard boundaries, skipped pre-grouping
# ---------------------------------------------------------------------------

def test_midstream_header_skipped_and_merge_equals_concat(tmp_path):
    a = [HEADER, rec(ident="m@f.h:3#1@integral=k/sample=0")]
    b = [HEADER, rec(ident="m@f.h:3#1@integral=k/sample=1", val=2.0)]
    ja, jb = write(tmp_path, a, "a.jsonl"), write(tmp_path, b, "b.jsonl")
    concat = tmp_path / "concat.jsonl"
    concat.write_bytes(ja.read_bytes() + jb.read_bytes())

    cfg = ReducerConfig()
    merged = core.merge_reports([core.reduce_journal(ja, cfg),
                                 core.reduce_journal(jb, cfg)])
    direct = core.reduce_journal(concat, cfg)
    for key in ("samples_seen", "no_id_records", "integrals", "nonfinite_records"):
        assert merged[key] == direct[key]
    assert direct["samples_seen"] == {"k": 2}


def test_midstream_schema_mismatch_hard_fails(tmp_path):
    lines = [HEADER, rec(), {"schema": 2}, rec()]
    j = write(tmp_path, lines)
    with pytest.raises(ValueError, match="mixed journal schemas"):
        core.reduce_journal(j)


# ---------------------------------------------------------------------------
# non-finite sentinel semantics: alarm direction, never benign
# ---------------------------------------------------------------------------

def test_nonfinite_cond_alarms_instead_of_reading_stable(tmp_path):
    """The review's verdict-inversion case: an exploding cond must NOT reduce
    to 'stable'. v1 maps it to the alarm clamp — same verdict as the legacy
    ±DBL_MAX clamp encoding of the same computation."""
    j = write(tmp_path, [HEADER, rec(cond="inf", rel_err="nan", val="inf")])
    cfg = ReducerConfig()
    rep = core.reduce_journal(j, cfg)
    assert rep["nonfinite_records"] == 1
    reg = next(iter(rep["integrals"]["k"]["regions"].values()))
    assert reg["max_cond"] == core.DBL_MAX_CLAMP
    assert reg["max_rel_err"] == core.DBL_MAX_CLAMP
    assert reg["abs_val_max"] == core.DBL_MAX_CLAMP

    final = core.finalize_report(core.merge_reports([rep]), cfg)
    region = next(iter(final["integrals"]["k"]["regions"].values()))
    assert region["signal_class"] == "local_cancellation"       # alarm, not stable
    assert region["value_range_ok_for_float"] is False          # range-unsafe

    # equivalence with the SAME computation journaled as legacy v0.3
    # (inf was clamped by the emitter; NaN was null -> the legacy 0.0 bug,
    # so rel_err differs by design — cond/val verdicts must match)
    jl = write(tmp_path, [rec(cond=1.7976931348623157e308, rel_err=None,
                              val=1.7976931348623157e308)], "legacy.jsonl")
    rep_l = core.reduce_journal(jl, cfg, legacy=True)
    reg_l = next(iter(rep_l["integrals"]["k"]["regions"].values()))
    assert reg_l["max_cond"] == reg["max_cond"]
    assert reg_l["abs_val_max"] == reg["abs_val_max"]
    assert reg_l["max_rel_err"] == 0.0                          # the legacy bug


def test_negative_inf_val_keeps_sign_then_abs(tmp_path):
    j = write(tmp_path, [HEADER, rec(val="-inf")])
    rep = core.reduce_journal(j)
    reg = next(iter(rep["integrals"]["k"]["regions"].values()))
    assert reg["abs_val_max"] == core.DBL_MAX_CLAMP


# ---------------------------------------------------------------------------
# the committed v1 fixture (generated by the post-break library)
# ---------------------------------------------------------------------------

def test_committed_v1_fixture_reduces_non_empty():
    cfg = ReducerConfig(predictions={"float": core.U_FLOAT, "ff": 2.0 ** -46})
    rep = core.reduce_journal(V1_FIXTURE, cfg)
    assert rep["no_id_records"] == 0
    assert len(rep["integrals"]) == 8
    assert all(cnt == 3 for cnt in rep["samples_seen"].values())
    # the range_overflow kernel journals NaN + Inf values -> sentinels mapped
    assert rep["nonfinite_records"] > 0
    # signals survive the v1 read end-to-end
    final = core.finalize_report(core.merge_reports([rep]), cfg)
    classes = {c for i in final["integrals"].values() for c in i["class_counts"]}
    assert "atan2_saturation" in classes and "cancellation_cascade" in classes

    # legacy mode must refuse it
    with pytest.raises(ValueError, match="not pre-v1"):
        core.reduce_journal(V1_FIXTURE, legacy=True)
