"""Differential-parity harness: tracked_tools.reduce vs the frozen AMP reducer.

The committed fixtures (tests/parity/fixtures/*.jsonl) are fresh v0.3-schema
journals generated by tests/parity/gen_fixtures.cpp with the PRE-schema-break
library.  The frozen reference (tests/parity/reference/) is a verbatim snapshot
of AMP's agents/shared/stability_reducer.py.  Parity = the ported core, given
the AMP-equivalent policy config, reproduces the reference byte-for-byte
(canonical JSON; floats compare equal because both run the identical Python
arithmetic).

After the v1 schema break, this harness runs the ported core in explicit
LEGACY-read mode (the plan's post-break criterion): the fixtures stay frozen
pre-v1 journals and the frozen AMP reference reads them natively.

The non-vacuousness tests exist because an empty report trivially equals an
empty report: they pin that the fixtures actually exercise every signal class,
both cascade-contributor detection paths, the saturation cap, the value-range
guard, and NaN/Inf value encodings.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

from tracked_tools.reduce import ReducerConfig, core

REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "tests" / "parity" / "fixtures"
GOLDENS = REPO / "tests" / "parity" / "goldens"
REFERENCE = REPO / "tests" / "parity" / "reference" / "amp_stability_reducer_frozen.py"

SHARDS = ["mixed_a", "mixed_b"]

# The AMP policy, expressed through the ported core's config seam: predictions
# for IEEE single and AMP's float-float emulation (empirical 2**-46 floor).
U_FF = 2.0 ** -46


def amp_config() -> ReducerConfig:
    return ReducerConfig(predictions={"float": core.U_FLOAT, "ff": U_FF})


@pytest.fixture(scope="module")
def frozen():
    spec = importlib.util.spec_from_file_location("amp_frozen", REFERENCE)
    mod = importlib.util.module_from_spec(spec)
    # dataclass processing requires the module to be importable by name
    sys.modules["amp_frozen"] = mod
    spec.loader.exec_module(mod)
    return mod


def canonical(obj: dict) -> str:
    return json.dumps(obj, indent=2, sort_keys=True)


def assert_same(new: dict, ref: dict) -> None:
    """Byte-compatible compare: canonical JSON equality (parsed-value floats)."""
    if new == ref:
        assert canonical(new) == canonical(ref)
        return
    # produce a readable first-divergence message
    def walk(a, b, path):
        if type(a) is not type(b) and not (
                isinstance(a, (int, float)) and isinstance(b, (int, float))):
            raise AssertionError(f"type mismatch at {path}: {type(a)} vs {type(b)}")
        if isinstance(a, dict):
            if set(a) != set(b):
                raise AssertionError(
                    f"key mismatch at {path}: only-new={set(a)-set(b)} "
                    f"only-ref={set(b)-set(a)}")
            for k in a:
                walk(a[k], b[k], f"{path}.{k}")
        elif isinstance(a, list):
            if len(a) != len(b):
                raise AssertionError(f"length mismatch at {path}: {len(a)} vs {len(b)}")
            for i, (x, y) in enumerate(zip(a, b)):
                walk(x, y, f"{path}[{i}]")
        elif a != b:
            raise AssertionError(f"value mismatch at {path}: {a!r} vs {b!r}")
    walk(new, ref, "$")
    raise AssertionError("dicts unequal but no divergence found")


# ---------------------------------------------------------------------------
# Differential parity: new core (AMP config) vs frozen AMP reducer
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("shard", SHARDS)
def test_shard_parity(frozen, shard):
    fix = FIXTURES / f"{shard}.jsonl"
    ref = frozen.reduce_journal(fix)
    new = core.reduce_journal(fix, amp_config(), legacy=True)
    assert_same(new, ref)


def test_merge_and_finalize_parity(frozen):
    fixes = [FIXTURES / f"{s}.jsonl" for s in SHARDS]
    ref = frozen.finalize_report(
        frozen.merge_reports([frozen.reduce_journal(f) for f in fixes]))
    cfg = amp_config()
    new = core.finalize_report(
        core.merge_reports([core.reduce_journal(f, cfg, legacy=True) for f in fixes]), cfg)
    assert_same(new, ref)


# ---------------------------------------------------------------------------
# Golden files (guard against reference/environment drift; used by CI)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("shard", SHARDS)
def test_shard_golden(shard):
    new = core.reduce_journal(FIXTURES / f"{shard}.jsonl", amp_config(), legacy=True)
    golden = json.loads((GOLDENS / f"{shard}.shard.json").read_text(encoding="utf-8"))
    assert_same(new, golden)


def test_final_golden():
    cfg = amp_config()
    new = core.finalize_report(
        core.merge_reports([core.reduce_journal(FIXTURES / f"{s}.jsonl", cfg, legacy=True)
                            for s in SHARDS]), cfg)
    golden = json.loads((GOLDENS / "final.report.json").read_text(encoding="utf-8"))
    assert_same(new, golden)


# ---------------------------------------------------------------------------
# Non-vacuousness: the fixtures must exercise the signals, or parity means
# nothing (the pre-v0.3 AMP fixtures reduced to an EMPTY report)
# ---------------------------------------------------------------------------

def test_reports_non_empty_and_exercise_signals():
    cfg = amp_config()
    shard_a = core.reduce_journal(FIXTURES / "mixed_a.jsonl", cfg, legacy=True)
    shard_b = core.reduce_journal(FIXTURES / "mixed_b.jsonl", cfg, legacy=True)

    for shard, n_samples in ((shard_a, 12), (shard_b, 8)):
        # v0.3 fixtures: every record carries an id
        assert shard["no_id_records"] == 0
        assert len(shard["integrals"]) == 8
        assert all(cnt == n_samples for cnt in shard["samples_seen"].values())
        for name, idata in shard["integrals"].items():
            assert idata["regions"], f"no regions for {name}"
            assert sum(r["n"] for r in idata["regions"].values()) > 0

        # both cascade-contributor detection paths produce chains:
        # cancellation = leaf-operand cond fallback; variance = val-based ratio
        assert shard["integrals"]["cancellation"]["cascade_chains"]
        assert shard["integrals"]["variance_cascade"]["cascade_chains"]

        # saturation cap (gate-a) present
        gate_a = sum(r["gate_a_count"]
                     for i in shard["integrals"].values()
                     for r in i["regions"].values())
        assert gate_a > 0

    final = core.finalize_report(core.merge_reports([shard_a, shard_b]), cfg)
    classes = {c for i in final["integrals"].values() for c in i["class_counts"]}
    assert {"stable", "log_near_root", "local_cancellation",
            "cancellation_cascade", "atan2_saturation"} <= classes

    # value-range guard fires on the overflow kernel...
    flags = [r["value_range_ok_for_float"]
             for r in final["integrals"]["range_overflow"]["regions"].values()]
    assert False in flags and True in flags
    # ...on BOTH sides: some region violates specifically the underflow bound
    assert any(r["abs_val_min"] is not None
               and r["abs_val_min"] < core.FLT_MIN_NORMAL
               and (r["abs_val_max"] is None or r["abs_val_max"] <= core.FLT_MAX)
               for i in final["integrals"].values()
               for r in i["regions"].values())

    # cascade chains hit both sides of chain_range_ok: the cascade_range
    # kernel's chains are range-UNSAFE (its contributor line under-flows
    # float), everything else's are safe — so the non-fail-open branch is
    # exercised, not just the default-True path
    chain_flags = {c["value_range_ok_for_float"]
                   for i in final["integrals"].values()
                   for c in i["cascade_chains"]}
    assert chain_flags == {True, False}
    assert all(c["value_range_ok_for_float"] is False
               for c in final["integrals"]["cascade_range"]["cascade_chains"])

    # prediction fields present for both configured formats
    a_region = next(iter(final["integrals"]["cancellation"]["regions"].values()))
    assert "predicted_rel_err_if_float" in a_region
    assert "predicted_rel_err_if_ff" in a_region


def test_fixture_encodings_and_cascade_branch_split():
    """Pin fixture properties the differential tests silently rely on."""
    raw_a = (FIXTURES / "mixed_a.jsonl").read_text(encoding="utf-8")
    # legacy NaN and +/-Inf encodings present (null / clamped DBL_MAX)
    assert '"val":null' in raw_a
    assert "1.7976931348623157e+308" in raw_a

    # the two cascade-contributor detection branches: in the cancellation
    # kernel the near-cancelling sub reads LEAF operands (track vars) so the
    # val-based ratio is unknowable (None -> cond fallback); in the variance
    # kernel it reads INTERNAL nodes so the val-based ratio is used.
    records = [json.loads(l) for l in raw_a.splitlines()]
    by_scope = {}
    for r in records:
        by_scope.setdefault(core._scope_str(r.get("id", "")).split("/")[0], []).append(r)

    def near_cancel_sub(recs, nodes):
        subs = [r for r in recs if r["op"] == "sub" and core._cond(r) > 1e6]
        assert subs
        return core._cancellation_ratio(subs[0], nodes)

    canc = by_scope["integral=cancellation"]
    nodes = {r["id"]: r for r in canc}
    assert near_cancel_sub(canc, nodes) is None          # leaf-fallback branch

    var = by_scope["integral=variance_cascade"]
    nodes = {r["id"]: r for r in var}
    ratio = near_cancel_sub(var, nodes)
    assert ratio is not None and ratio < 0.1             # val-based branch


def test_merge_associativity(tmp_path):
    """merge([reduce(A), reduce(B)]) == reduce(A ++ B)."""
    cfg = amp_config()
    concat = tmp_path / "concat.jsonl"
    concat.write_bytes((FIXTURES / "mixed_a.jsonl").read_bytes()
                       + (FIXTURES / "mixed_b.jsonl").read_bytes())
    merged = core.merge_reports([core.reduce_journal(FIXTURES / "mixed_a.jsonl", cfg, legacy=True),
                                 core.reduce_journal(FIXTURES / "mixed_b.jsonl", cfg, legacy=True)])
    direct = core.reduce_journal(concat, cfg, legacy=True)
    # kinds differ by design (merged vs shard); compare the payload
    for key in ("samples_seen", "no_id_records", "integrals"):
        assert_same(merged[key], direct[key])


def test_cli_smoke(tmp_path):
    from tracked_tools.reduce import cli
    out = tmp_path / "report.json"
    rc = cli.main(["--legacy", "--predict", f"ff={U_FF!r}",
                   "report", str(FIXTURES / "mixed_a.jsonl"),
                   str(FIXTURES / "mixed_b.jsonl"), "-o", str(out)])
    assert rc == 0
    rep = json.loads(out.read_text(encoding="utf-8"))
    golden = json.loads((GOLDENS / "final.report.json").read_text(encoding="utf-8"))
    assert_same(rep, golden)


def test_cli_reduce_and_merge(tmp_path):
    """The reduce and merge subcommands round-trip to the same goldens."""
    from tracked_tools.reduce import cli
    predict = ["--predict", f"ff={U_FF!r}"]
    shard_files = []
    for shard in SHARDS:
        out = tmp_path / f"{shard}.shard.json"
        rc = cli.main(["--legacy", *predict, "reduce", str(FIXTURES / f"{shard}.jsonl"),
                       "-o", str(out)])
        assert rc == 0
        golden = json.loads((GOLDENS / f"{shard}.shard.json").read_text(encoding="utf-8"))
        assert_same(json.loads(out.read_text(encoding="utf-8")), golden)
        shard_files.append(out)

    out = tmp_path / "merged.report.json"
    rc = cli.main([*predict, "merge", *map(str, shard_files), "-o", str(out)])
    assert rc == 0
    golden = json.loads((GOLDENS / "final.report.json").read_text(encoding="utf-8"))
    assert_same(json.loads(out.read_text(encoding="utf-8")), golden)
